name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Ubuntu
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: cargo build --release
  build-windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: cargo build --release
  build-mac:
    runs-on: macos-latest
    name: Build on macOS
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: cargo build --release
